### ISSUE TITLE
Notification center

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx-frontend#150]
Handle two types of notifications:
* flash messages: 
  * Should appear once and disappear on next request or on user interaction
  * Examples:
    * Process started notification
    * Form error messages
* Notifications
  * Should appear in an notification center (maybe sidebar) and there should be an icon showing number of new notifications
  * User has to mark these notifications as read
  * Examples
    * Process finished notification (new download) -> download link

If this feature will be implemented: **Replace stored messages** by own implementation.

**Comment by hixi** [comment]
Closing, most of the functionality described here is already implemented.
