### ISSUE TITLE
Move BaseExcerptConverter.inform_user() to class User

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx-frontend#159]
and make [it](https://github.com/geometalab/osmaxx/blob/feature/excerptConverters%23123/osmaxx-py/excerptconverter/baseexcerptconverter/base_excerpt_converter.py#L36) an instance method instead of a `@staticmethod`

**Comment by das-g** [comment]
Note: We don't have a User class of our own, yet. Should we create one? Can we derive from the provided User class we currently use?

**Comment by njordan-hsr** [comment]
When we do (not making a statement about if we should or not), it should be a separate app, maybe namespaced under osmaxx. We don't [reference](https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#referencing-the-user-model) the User class correctly though to use a [custom user](https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#substituting-a-custom-user-model).

**Comment by hixi** [comment]
has changed since, is good enough as is. Closing.
