### ISSUE TITLE
Webapp: Treat validations errors on service calls as validation errors on the webapp request that triggerd them (create action)

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx-frontend#20]
Estimated duration: ~2d

check for

* valid coordinates
* options
* not empty required fields
* ...

in case of constraint violation:
* send user back to form, with his entered data pre-filled (including data violating constraints)
* disable button and indicate constraint violation as in #19 (might implicitly be handled by implementation of #19, anyway)

**Comment by njordan-hsr** [comment]
Maybe a good call for http://django-crispy-forms.readthedocs.org/en/latest/crispy_tag_forms.html#fundamentals ?

**Comment by das-g** [comment]
Validation is done by calling the conversion service (which will itself validate). In this issue, correct reaction to validation errors signalled by the service shall be implemented.

**Comment by hixi** [comment]
@wasabideveloper @das-g 
I think we're not able to integrate this into 1.0 release, is it ok to push this into 2.0?

**Comment by hixi** [comment]
Closing.
