### ISSUE TITLE
deployment-script: run manage.py check --deploy during automated deployment

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx-frontend#233]
The deployment script [should run `manage.py check --deploy`](https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/#run-manage-py-check-deploy) on the target server and abort with a failure if these checks come up with any complaints.

**Comment by njordan-hsr** [comment]
We should aim for automatic deployment some time soon(ish) and run this check, if it fails, do not deploy.

**Comment by hixi** [comment]
this issue now applies to [osmaxx-deployment-scripts](https://github.com/geometalab/osmaxx-deployment-scripts), which handles deployment.

**Comment by hixi** [comment]
This now has no relevance, since deployment isn't being handled by the project itself anymore. But it still needs documentation for people, who would like to deploy the service themselves.

**Comment by hixi** [comment]
Not necessary anymore, handled separately, closing.
