### ISSUE TITLE
webapp: request file deletion if retrieval was successful

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-frontend#289]
request file deletion on other side if retrieval was successful (use URL from status request answer).

Is split out from #247

**Comment by hixi** [comment]
How do we know, file retrieval was successful? 
- MD5 checksum? -> implementation on service side needed
- other ideas?

@das-g @wasabideveloper 
Proposition: move to cleanup or even 2.0

**Comment by das-g** [comment]
Not relevant or visible to users. Moving to Cleanup Milestone.

**Comment by das-g** [comment]
Providing one or several hashes on the service API sounds like a good idea. Calculating them shouldn't be a problem. We can either use the respective command line tools or Python's [hashlib](https://docs.python.org/3/library/hashlib.html) with the approach from [here](http://stackoverflow.com/a/1131238/674064) (to avoid loading the whole file into memory at once).

**Comment by wasabideveloper** [comment]
I think checksum is a bit overengineered. There will be connection between the containers or not. We won't get often the problem of not completely downloaded files. So we just have to check if the file is there and if no error occured during download and then we can delete the file on the other side.

**Comment by hixi** [comment]
See geometalab/osmaxx-frontend#139 for more information.

**Comment by hixi** [comment]
Solved by using a storage connection, closing.
