### ISSUE TITLE
create symbol font from point markers in individual SVG files

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-frontend#333]
create a pipeline, which allows to convert the created svg to a symbolfont and use that in QGis.
Should be more or less automatically recreated whenever updated.

**Comment by hixi** [comment]
Maybe https://github.com/carrasti/pysvg2font is a possible candidate for use.

**Comment by hixi** [comment]
Converting to font (ttf) should be done for the svg at:
https://github.com/geometalab/osmaxx-docs/tree/master/osmaxx-symbology/OSMaxx_point_symbols

For a comparison, also the [original svgs](https://github.com/geometalab/osmaxx-docs/tree/master/osmaxx-symbology/original) should be converted to a font.

**Comment by sfkeller** [comment]
Creating a font with Windows from SVG input:
* Inkscape (open source) plus online-font-coverter: https://www.youtube.com/watch?v=_KX-e6sijGE
* FontForge 
* BirdFont
* See also http://giswiki.hsr.ch/Symbolkatalog
