### ISSUE TITLE
Country deprecation strategy

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-frontend#341]
- [ ] use country / subregion ISO codes as IDs (maybe augmented with a version)
- [ ] decide how deprecated countries / subregions are represented on the API
  - suggestion:
    - Countries (or country versions) are retained indefinitely by the service
    - service advertises which of those can be used for new extractions (options header)
    - deprecated countries / versions can still be references by existing excerpts

---

https://sentry.dev.njo.ch/geometalab/osmaxx-dev/group/24/

```
KeyError: 'name'
(19 additional frame(s) were not displayed)
...
  File "osmaxx/excerptexport/models/extraction_order.py", line 64, in __str__
    ', state: ' + self.get_state_display() + ', output files: ' + str(self.output_files.count())
  File "osmaxx/excerptexport/models/extraction_order.py", line 72, in excerpt_name
    return get_authenticated_api_client().get_country_name(self.country_id)
  File "osmaxx/excerptexport/services/conversion_api_client.py", line 216, in get_country_name
    return self.get_country(country_id)['name']
```

Because we removed some bigger countries, the old excerpts failed to load. We probably need to make this interface more robust, so that the list can be viewed nonetheless.

**Comment by das-g** [comment]
We need a strategy how deprecating countries is handled between service and front-end.

Persistent IDs that are exposed should be reproducibly assigned. (Currently they come from a migration.)

**Comment by hixi** [comment]
Original issue has been remedied through moving the countries to the frontend. Therefore: YAGNI, can be done with a migration if ever needed, since new countries need a migration anyway. Closed
