### ISSUE TITLE
Show map on full right half

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx-frontend#355]
On big screens the map will not fit the full right half of the screen.

**Comment by das-g** [comment]
Can you provide a screenshot that demonstrates this bug?

I guess it's the size of the browser window (or more precisely of the page's viewport in it), not the screen size that matters here, but wasn't able to reproduce this, yet.

**Comment by wasabideveloper** [comment]
@hixi It happens on your big screen. Please take a screenshot.

**Comment by hixi** [comment]
![not_full_size](https://cloud.githubusercontent.com/assets/97119/12166971/b5bd2132-b529-11e5-98f5-f9576f723954.png)

**Comment by hixi** [comment]
Update: Only occurs on Chrome

**Comment by hixi** [comment]
Doesn't occur anymore in the newest Chrome, closing.
