### ISSUE TITLE
Improve file format naming consistency

### ISSUE THREAD

**Issue by wasabideveloper** [geometalab/osmaxx-frontend#357]
Name file formats everywhere the same:
* Downloads `osmaxx/web_frontend/osmaxx/excerptexport/templates/excerptexport/partials/content_file_type_description.html`
* Extraction Options `/home/tblaser/Projects/Osmaxx/osmaxx/web_frontend/osmaxx/excerptexport/forms/order_options_mixin.py`
* Download file name: Settings > download_file_name

ESRI File Geodatabase (FileGDB)
ESRI Shapefile (shp)
GeoPackage (gpkg)
SQLite based SpatiaLite (spatialite)
Garmin navigation & map data (img, tdb)

**Comment by das-g** [comment]
My understanding of the names, as used outside of the osmaxx project:

| Long name                    | Short names / Abbreviations | filename extensions      |
|------------------------------|-----------------------------|--------------------------|
| ESRI File Geodatabase        | FileGDB, FGDB               | gdb (used on directory)  |
| ESRI Shapefile               | Shapefile                   | shp, shx, dbf and others |
| GeoPackage                   | GPKG                        | gpkg                     |
| SpatiaLite                   |                             | sqlite                   |
| Garmin navigation & map data |                             | img, tdb                 |

**Comment by das-g** [comment]
TBD: What name(s) should be used/displayed where?

**Comment by das-g** [comment]
@hixi and I agreed on:

| Long name                    | Short names / Abbreviations | filename extensions      | technical identifyer (not shown to end user) | archive name component |
|------------------------------|-----------------------------|--------------------------|----------------------------------------------|------------------------|
| ESRI File Geodatabase        | FileGDB, FGDB               | gdb (used on directory)  | fgdb                                         | FileGDB                |
| ESRI Shapefile               |                             | shp, shx, dbf and others | shapefile                                    | Shapefile              |
| GeoPackage                   | GPKG                        | gpkg                     | gpkg                                         | GeoPackage             |
| SpatiaLite                   |                             | sqlite                   | spatialite                                   | SpatiaLite             |
| Garmin navigation & map data |                             | img, tdb                 | garmin                                       | Garmin                 |


### Display on web pages (options on forms, order status page):
`<strong>{Long name}</strong> ({Short names, if any})`
or
`{Long name} <small>({Short names, if any})`

(without parens if there are no short names)

### Emails:
`{Long name} ({Short names, if any})`

### Technical identifiers
Must be coordinated between frontend and conversion-service!
