### ISSUE TITLE
prefer HttpRequest.build_absolute_uri() over string manipulation for building own absolute URLs

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx-frontend#362]
We manually build URLs from the current request's protocol and host combined with a context-dependant path [for the callback URL we send to the conversion service for newly created jobs](https://github.com/geometalab/osmaxx/blob/52a2d08d1bc0806310209c95675f8d8d73655ff5/web_frontend/osmaxx/excerptexport/services/conversion_api_client.py#L77), [for the links in the list of downloads](https://github.com/geometalab/osmaxx/blob/52a2d08d1bc0806310209c95675f8d8d73655ff5/web_frontend/osmaxx/excerptexport/templates/excerptexport/partials/download_list.html#L17) and for the [email content there](https://github.com/geometalab/osmaxx/blob/52a2d08d1bc0806310209c95675f8d8d73655ff5/web_frontend/osmaxx/excerptexport/templates/excerptexport/partials/download_list.html#L11) ([also here](https://github.com/geometalab/osmaxx/blob/52a2d08d1bc0806310209c95675f8d8d73655ff5/web_frontend/osmaxx/excerptexport/templates/excerptexport/partials/send_all_links.html#L3)).

We should consider using [`HttpRequest.build_absolute_uri(location)`](https://docs.djangoproject.com/en/1.9/ref/request-response/#django.http.HttpRequest.build_absolute_uri) instead.

**Comment by hixi** [comment]
:+1: I'm all in favor of using `request.build_absolute_uri(location)` - it uses the current request (context), so this is only possible in cases where there is one - I can't find the example, but I think we used it without it at least in one place.

**Comment by das-g** [comment]
> I can't find the example, but I think we used it without [the current request] at least in one place.

That might have been on the [`osmaxx-conversion-service`](https://github.com/geometalab/osmaxx-conversion-service) side.

B.t.w., the occurrences above, I've found with `git grep '://{'`.

**Comment by hixi** [comment]
That sounds very plausible that we're having that issue there.
