### ISSUE TITLE
Support OsmAnd map (*.obf) as export format

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx-frontend#378]
As a user of OSM map and/or navigation on an Android mobile device (phone, phablet, tablet or other that can run [OsmAnd](http://osmand.net/)), I don't want to use up my allowance of free OsmAnd country map downloads too quickly, but I'm also not eager on converting `*.osm` or `*.osm.pbf` files (which I could obtain from osmaxx once #167 is implemented, or get from somewhere else) to `*.obf` files myself. Thus, I'd appreciate if I could get them created for my osmaxx excerpts by osmaxx.

### Workaround:
As long as you _only_ need maps already provided by OsmAnd (or anyone else), you can use [F-Droid's **OsmAnd~** build](https://f-droid.org/repository/browse/?fdid=net.osmand.plus), which (if I understand [the OSM wiki](http://wiki.openstreetmap.org/w/index.php?title=OsmAnd&oldid=1251646#Download_.26_installation) correctly) doesn't have a limitation on map downloads.

An osmaxx feature, in contrast, would allow for maps of arbitrary (user-defined) excerpts.

---

#### Note
"User" in this story would be e.g., me, @das-g. This story is **not** (yet?) a request from our contractees.

---

#### Implementation note:
For creation of `*.obf` files see [OSM wiki: OsmAndMapCreator > Regular Creation of OBF Files (via Command Line)](http://wiki.openstreetmap.org/wiki/OsmAndMapCreator#Regular_Creation_of_OBF_Files_.28via_Command_Line.29).

**Comment by hixi** [comment]
I'm in favor of closing this issue, since it isn't required for the project. If it should be wished for at a later point, we can re-open it.

**Comment by das-g** [comment]
Closing (for now) in favor of #380
