### ISSUE TITLE
Add link to OsmAnd

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-frontend#380]
Near format choices, add a link to OsmAnd, as an alternative to garmin.

**Comment by hixi** [comment]
This link clutters the form. We agreed to put the link and more information on it on a separate static page, this issue is now part of #434

**Comment by das-g** [comment]
> We agreed to put the link and more information on it on a separate static page, this issue is now part of #434

We = @hixi  and me, in this case
