### ISSUE TITLE
add integration tests

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx-frontend#402]
End-to-end tests were broken and thus removed in #401. Create selenium integration tests to replace one aspect of them.

**Comment by hixi** [comment]
Documentation on selenium with pytest:
http://pytest-selenium.readthedocs.org/en/latest/

Branch: #402_add_integration_tests

Startup the project:

```bash
docker-compose pull
docker-compose up -d conversionservicepostgres database
# wait at least 10 seconds
docker-compose run webapp /bin/bash -c './manage.py createsuperuser'
# create and remember the user created, needed for tests!
docker-compose run --rm osmplanet
docker-compose up frontend mediator worker
```

in a separate window:

create a new virtualenv and install dependencies:

```bash
virtualenv --python=/usr/bin/python3 ~/tmp/osmaxx_integration_test
. /tmp/osmaxx_integration_test/bin/activate
pip install -r requirements.txt
```

If this has been done once, only `. ~/tmp/osmaxx_integration_test/bin/activate` is needed.

Create new tests under `tests/`

run the tests with:

`py.test tests`
