### ISSUE TITLE
Contract Substation types

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-frontend#419]
all substation types should be contracted to one substation. (sub-station and substation tags, maybe more?)

**Comment by das-g** [comment]
Looks like we already unify the tag values `sub_station` and `substation` to only `substation` for tag key `power` [for Layers `utility_p`](https://github.com/geometalab/osmaxx-conversion-service/blob/aa93268549c65c148a725d05cef8f1de8eff60d4/osmaxx/converters/gis_converter/bootstrap/sql/filter/utility/040_utility_p_power.sql#L13) and [`utility_a`](https://github.com/geometalab/osmaxx-conversion-service/blob/aa93268549c65c148a725d05cef8f1de8eff60d4/osmaxx/converters/gis_converter/bootstrap/sql/filter/utility/010_utility_a_power.sql#L14).

@cdeUG, @geoSLG can you provide an example (tag combination or OSM id of actual feature) that doesn't work as expected?

**Comment by geoSLG** [comment]
There are certain points listed as type = power, but should be substations
e.g. the following:
•	OSM_ID 385870453 _Tag: "power"=>"substation", "osm_uid"=>"2644617", "osm_user"=>"Jimiiee", "way_area"=>"3.97586e-06", "osm_version"=>"1", "osm_changeset"=>"35949478", "osm_timestamp"=>"2015-12-14T16:34:10Z"

•	OSM_ID 385873221
•	OSM_ID 387365829
•	OSM_ID 344593713
seems like features with value = substation are listed in type = power, while features with value = sub_station are listed in Type= substation

**Comment by das-g** [comment]
Thanks. We'll have a look.

**Comment by das-g** [comment]
> Looks like we already unify the tag values `sub_station` and `substation` to only `substation` for tag key `power` [for Layers `utility_p`](https://github.com/geometalab/osmaxx-conversion-service/blob/aa93268549c65c148a725d05cef8f1de8eff60d4/osmaxx/converters/gis_converter/bootstrap/sql/filter/utility/040_utility_p_power.sql#L13) and [`utility_a`](https://github.com/geometalab/osmaxx-conversion-service/blob/aa93268549c65c148a725d05cef8f1de8eff60d4/osmaxx/converters/gis_converter/bootstrap/sql/filter/utility/010_utility_a_power.sql#L14).

Ah, I was mistaken: We currently unify (deprecated, but still in use) OSM tags [`power=station`](http://wiki.openstreetmap.org/wiki/Tag:power%3Dstation) and [`power=sub_station`](http://wiki.openstreetmap.org/wiki/Tag:power%3Dsub_station) to aggtype `substation` and type `station`, but indeed missed the now recommended [`power=substation` tag](http://wiki.openstreetmap.org/wiki/Tag:power%3Dsubstation). So for `power=substation`, the fallback aggtype 'power' and fallback type 'power' for `power=*` OSM tags kicked in.

> all substation types should be contracted to one substation. (sub-station and substation tags, maybe more?)

[It doesn't look like `power=sub-station` is in use.](http://taginfo.openstreetmap.org/search?q=power%3D%22sub-station%22)

We'll change this so that OSM tag `power=substation` will be handled just like OSM tags `power=station` and `power=sub_station`.

**Comment by das-g** [comment]
@sfkeller: Deprecated OSM tag [`power=sub_station`](http://wiki.openstreetmap.org/wiki/Tag:power%3Dsub_station) is unambigous, but should we really treat the other deprecated OSM tag [`power=station`](http://wiki.openstreetmap.org/wiki/Tag:power%3Dstation) as electrical substation? While that was that tag's originally intended meaning, the reason it was deprecated is that it was often confused with the British English term "power station" (a synonym for a power plant) and thus used for power plants and electrical substations alike (by different mappers, supposedly).

So wouldn't it more appropriate to simply fall back to type and aggtype "power" for `power=station`?

**Comment by geoSLG** [comment]
The problem is that all features with the tags [power=sub_station ](http://wiki.openstreetmap.org/wiki/Tag:power%3Dsub_station) are listed with the attributes: "aggtype" = substation and "type" = substation, while power=substation has the attributes "aggtype"=power and "type"= power. 
[power=substation ](http://wiki.openstreetmap.org/wiki/Tag:power%3Dsubstation) should have the attributes substation as well.

**Comment by geoSLG** [comment]
as [power=station](http://wiki.openstreetmap.org/wiki/Tag:power%3Dstation) shouldn't be used anymore and has been replaced with the tag power=substation. I'd propose to use the attributes aggtype=substation and type=substation

**Comment by das-g** [comment]
> The problem is that all features with the tags power=sub_station are listed with the attributes: "aggtype" = substation and "type" = substation, while power=substation has the attributes "aggtype"=power and "type"= power.

Yes, that's what I wrote in [my comment above](https://github.com/geometalab/osmaxx-frontend/issues/419#issuecomment-221505970), isn't it?

> power=substation should have the attributes substation as well.

Indeed, that's what I'm changing here. See 98580ed / PR #510 

> as power=station shouldn't be used anymore and has been replaced with the tag power=substation. I'd propose to use the attributes aggtype=substation and type=substation

While it "has been recommended to stop using it", `power=station` is still quite prevalent in today's OSM data ([map](http://taginfo.openstreetmap.org/tags/power=station#map)).

While its _intended_ meaning _was_ that of an electrical substation, it has mistakenly been used to tag power plants, too, if the OSM wiki is to be believed.

@geoSLG Do you propose to map it to aggtype `substation` and type `substation` anyway?
@sfkeller Do you agree?

If so, I'll leave it at the 98580ed change. :smile:

**Comment by das-g** [comment]
Decision taken at today's conference call: Keep mapping OSM tag `power=station` to OSMaxx attributes aggtype `substation` and type `substation`.

Reason: According to @cdeUG and @geoSLG, there are no plans to make aggtype `power` or type `power` (the fallback values for electricity stuff we can't categorize) visible in the OSMaxx default symbolizations on any zoomlevel. Not having these features appear on the map at all would be worse than having them appear with a wrong symbolization in case of misapplied OSM tag `power=station` on e.g. power plants.

**Comment by cdeUG** [comment]
Yes right. Putting tag `power=station` to aggtype  `power `resp. type `power` means it will not be visible on the map, as type `power `is not intended to be added on a any of the different map templates (M1, M3, M4 etc. So, it is better to keep it as aggtype `substation `and type `substation` to prevent loosing important information.
