### ISSUE TITLE
add classification to `nonop` features

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-frontend#423]
To be decided: how should the column be named

Add a new column, ie. `sub_type` which holds which sepcific type it is

**Comment by das-g** [comment]
[For roads](http://wiki.openstreetmap.org/wiki/Highways#Classification), this should probably be the value of the [`highway=*` OSM tag](http://wiki.openstreetmap.org/wiki/Key:highway).

[For railways](http://wiki.openstreetmap.org/wiki/Railways#Types_of_railway_line), this should probably be the value of the [`railway=*` OSM tag](http://wiki.openstreetmap.org/wiki/Key:railway).

> To be decided: how should the column be named

Suggestions: `classification` or `sub_type`

**Comment by geoSLG** [comment]
> `sub_type` is good.
If column `type` in the table nonop_l stays as it is, the new column can be called `sub_type`

**Comment by das-g** [comment]
> [For roads](http://wiki.openstreetmap.org/wiki/Highways#Classification), this should probably be the value of the [`highway=*` OSM tag](http://wiki.openstreetmap.org/wiki/Key:highway).
> 
> [For railways](http://wiki.openstreetmap.org/wiki/Railways#Types_of_railway_line), this should probably be the value of the [`railway=*` OSM tag](http://wiki.openstreetmap.org/wiki/Key:railway).

Considering [the `<key> = <status>` + `<status> = <value>` tagging scheme](http://wiki.openstreetmap.org/wiki/Comparison_of_life_cycle_concepts#.3Ckey.3E_.3D_.3Cstatus.3E_.2B_.3Cstatus.3E_.3D_.3Cvalue.3E) (which is the one [our `WHERE` clause](https://github.com/geometalab/osmaxx-frontend/blob/b31655e38646ced333a16608f4bf3ab64a4eaa11/osmaxx/conversion/converters/converter_gis/bootstrap/sql/filter/nonop/010_nonop.sql#L53) currently detects), that won't work, of course. Instead, the value of the `<status> = *` tag has to be treated as if it were the main key's value.
