### ISSUE TITLE
Static About Site

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-frontend#434]
- [x] create a static page with information about the OSMaxx project.
- [x] Link to that page in footer.
- [x] Add Impressum section as well.
- [x] Add link and explanation to OsmAnd #380

**Comment by hixi** [comment]
@sfkeller do you know what should/needs to be included in the `about us` section (impressum, information about the team, contact...)?

**Comment by sfkeller** [comment]
Don't forget to add an information where OSMaxx declares which data sources where used besides.
