### ISSUE TITLE
GeoPackage exports should be usable in QGIS

### ISSUE THREAD

**Issue by das-g** [geometalab/osmaxx-frontend#493]
### To reproduce

1. export something to GeoPackage, wait for it to finish and download the file<br />(Mine is available on  `http://<production domain>/downloads/484a0633-38ca-4f06-a1a3-621dc2903882/`.)
2. unpack the Zip archive (`2016-05-13-FrankfurtamMain-484a0633-38ca-4f06-a1a3-621dc2903882.gpkg.zip` in my case)
3. drag & drop `*.gpkg/data/*_gpkg.gpkg` (`2016-05-13-FrankfurtamMain-484a0633-38ca-4f06-a1a3-621dc2903882.gpkg/data/20160513-frankfurt-am-main_gpkg.gpkg` in my case) into the QGIS layers panel (or open it with `Layer` > `Add Layer` > `Add Vector Layer ...` / <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>v</kbd> / the according button)

#### Expected
The list of usual layers of the OSMaxx output schema is displayed, with the appropriate respective geometry types.

#### Observed
* The list of usual layers of the OSMaxx output schema is displayed, but with geometry type **None** for all of them
* Additional layers are displayed. The names look like it might be GeoPackage interna.
* After clicking **Select All** and **OK**, the layers are listed in the layers panel, but no geometries are displayed. Attribute tables can be viewed.

**Comment by das-g** [comment]
![screenshot from 2016-05-13 15 53 07](https://cloud.githubusercontent.com/assets/97746/15250004/da2af262-1922-11e6-8017-aa115f307a06.png)

**Comment by hixi** [comment]
Maybe we should investigate updating our [docker-gdal-with-FileGDB](https://github.com/geometalab/docker-gdal-with-FileGDB) image first, before trying to solve anything else?

**Comment by hixi** [comment]
This seems to be a bug in the QGIS version, it works alright here.

**Comment by das-g** [comment]
On QGIS 2.14.2-Essen, analogous unexpected behavior can be observed for GeoPackage files that weren't produced by OSMaxx:

- http://ngageoint.github.io/GeoPackage/examples/rivers.gpkg
- http://www.geopackage.org/data/simple_sewer_features.gpkg
- http://www.geopackage.org/data/gdal_sample.gpkg

So this is most probably a bug in QGIS.

Closing as invalid.
