### ISSUE TITLE
Remove and cleanup output-files

### ISSUE THREAD

**Issue by hixi** [geometalab/osmaxx-frontend#553]
After a certain duration (days, weeks....) cleanup the output-files and remove them.

Also see #368

**Comment by hixi** [comment]
@das-g Discussion needed on how to do the cleanup:
- limit per user output-files and remove their excerpt oldest files (ie. the oldest file, so that every excerpt keeps an output file as long as possible)
- remove every output file after a duration of two weeks (simpler solution, easier to communicate to user)

**Comment by das-g** [comment]
> - limit per user output-files and remove their excerpt oldest files (ie. the oldest file, so that every excerpt keeps an output file as long as possible)

While the above might be more "useful" and "fair" (keeping downloads of less active users longer around), I think I prefer
> - remove every output file after a duration of two weeks (simpler solution, easier to communicate to user)

as that is indeed easier to implement, easier to understand and easier to communicate. Also, easier to predict from the user's point of view, as they might themselves not be able to predict their own future actions. Further, easier to predict for people who get a download link from a user. (Actually, this is the only way the availability can be communicated to link receivers, as those can in general neither predict nor influence the user's future actions, nor usually know about those actions when they do happen.)
